# Generated by Django 5.0.14 on 2026-07-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tileproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='tileproduct',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='tileproduct',
            name='features',
        ),
        migrations.RemoveField(
            model_name='tileproduct',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='tileproduct',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='tileproduct',
            name='water_absorption',
        ),
    ]
