# Generated by Django 4.2.30 on 2026-07-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0002_alter_tileproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
