# Generated by Django 4.2.30 on 2026-07-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0003_alter_country_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tileproduct',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
