# Generated by Django 4.2.30 on 2026-07-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0006_generatedimage_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilecategory',
            name='usage_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', help_text='Whether the category is for residential or commercial projects', max_length=20),
        ),
    ]
