# Generated by Django 4.2.30 on 2026-08-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0011_ecommerce_orders_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='created', max_length=20),
        ),
    ]
